// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiA0eJm0J2rJfDK9NXguhFHP-aF2SvLrI',
    appId: '1:336311645957:web:88c0cf44c090195f74296c',
    messagingSenderId: '336311645957',
    projectId: 'newsapp-51b9e',
    authDomain: 'newsapp-51b9e.firebaseapp.com',
    storageBucket: 'newsapp-51b9e.appspot.com',
    measurementId: 'G-T8ZD61814G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzrpPCAO3A2CZ8f-m5ZeulPG7LdupbXc',
    appId: '1:336311645957:android:3b03898eff82889574296c',
    messagingSenderId: '336311645957',
    projectId: 'newsapp-51b9e',
    storageBucket: 'newsapp-51b9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsfJP4HsX7imJU-VAAv2SWP30S7WPhUnY',
    appId: '1:336311645957:ios:cde8db440d68942074296c',
    messagingSenderId: '336311645957',
    projectId: 'newsapp-51b9e',
    storageBucket: 'newsapp-51b9e.appspot.com',
    iosClientId: '336311645957-loj10r8hkc059hh5gk8l10jsf0qef6n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsfJP4HsX7imJU-VAAv2SWP30S7WPhUnY',
    appId: '1:336311645957:ios:cde8db440d68942074296c',
    messagingSenderId: '336311645957',
    projectId: 'newsapp-51b9e',
    storageBucket: 'newsapp-51b9e.appspot.com',
    iosClientId: '336311645957-loj10r8hkc059hh5gk8l10jsf0qef6n7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
